- name: Create a virtual machine
  hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: configuration
  - include_role:
      name: vm
    vars:
      subscription_code: "{{ (smiths_config_subscriptions | dict2items | json_query('[?value.name==`' ~ _input_subscription ~ '`].key'))[0] }}"
      location_code: "{{ (smiths_config_metadata.locations | dict2items | json_query('[?value.name==`' ~ _input_region ~ '`].key'))[0] }}"
      vnet_code: "{{ _input_network.split('/')[0] }}"
      subnet_code: "{{ _input_network.split('/')[1] }}"
