- name: Load subscription configuration 
  include_vars:
    file: subscriptions.yml

- name: Load networking configuration
  include_vars:
    file: networking.yml

- name: Load tag presets
  include_vars:
    file: tag-presets.yml

- name: Load regions
  include_vars:
    file: regions.yml