- name: Create Public IP
  azure_rm_deployment:
    deployment_name: "public_ip_{{ smiths_vm_name }}-nic01"
    resource_group_name: "{{ smiths_resource_group_name }}"
    location: "{{ smiths_region_name }}"
    template: "{{ lookup('file', '../../../arm-templates/public-ip.json') | from_json }}"
    tags: "{{ smiths_azure_tags }}"
    parameters:
      location:
        value: "{{ smiths_region_name }}"
      name:
        value: "{{ smiths_vm_name }}-nic01-ipv4-publicip"
      dnsName:
        value: "smiths-{{ smiths_vm_name }}-nic01"
      tags:
        value: "{{ smiths_azure_tags }}"
  register: smiths_public_ip_address_job

- name: Dump resource info
  debug:
    var: smiths_public_ip_address_job
