# Used for naming and tagging
smiths_environment_code_mapping:
  "Production": prd
  "Development": dev
  "Quality Assurance": qa
  "Test": tst
  "Staging": stg
smiths_environment_char_mapping:
  "Production": p
  "Development": d
  "Quality Assurance": q
  "Test": t
  "Staging": s
smiths_environment_code: "{{ smiths_environment_code_mapping[smiths_environment] | default('unknown') }}"
smiths_environment_char: "{{ smiths_environment_char_mapping[smiths_environment] | default('u') }}"
smiths_environment_name: "{{ smiths_environment | default('Unknown') }}"
