- name: Get facts
  azure_rm_resource_facts:
    api_version: "2018-08-01"
    resource_group: "bis-awx-dev-rg"
    resource_type: resources
  register: smiths_resources

- name: Apply tags
  azure_rm_resource:
    url: "{{ item.id }}"
    api_version: "{{ smiths_azure_resource_provider_api_versions[item.type] }}"
    method: PATCH
    body:
      tags: "{{ smiths_azure_tags }}"
  loop: "{{ smiths_resources.response[0].value }}"
